### ISSUE TITLE
Force encoding type with open()

### ISSUE THREAD

**Issue by Woovie** [ahtn/keyboard_case_and_pcb_gen#3]
I don't have my git environment set up on my Windows box right now, so forgive me for not simply creating a pull request.

```cmd
PS C:\Users\jbanasik\candy69\rev2> python.exe C:\Users\jbanasik\pcbgen\plate.py --margin 19 C:\Users\jbanasik\candy69\rev2\candy69-rev2.json
Traceback (most recent call last):
  File "C:\Users\jbanasik\pcbgen\plate.py", line 837, in <module>
    json_file_contents = json_file.read()
  File "C:\Users\jbanasik\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1502: character maps to <undefined>
PS C:\Users\jbanasik\candy69\rev2> python.exe C:\Users\jbanasik\pcbgen\plate.py --margin 19 C:\Users\jbanasik\candy69\rev2\candy69-rev2.json
```

The issue here is that open() is using the wrong encoding. I think it's not able to determine the encoding of the .json so it is trying cp1252, which is very, very wrong.

Here's my .patch

```cmd
--- plate_old.py        2018-04-15 13:11:40.952959500 -0500
+++ plate.py    2018-04-15 13:07:30.107000200 -0500
@@ -833,7 +833,7 @@
                 raise

     json_layout = None
-    with open(args.kle_json_file) as json_file:
+    with open(args.kle_json_file, encoding="utf8") as json_file:
         json_file_contents = json_file.read()
         if file_ext == ".json":
             json_layout = json.loads(json_file_contents)
```

**Comment by ahtn** [comment]
should be fixed now, f487667
